### ISSUE TITLE
Special currency pattern for numbers with no decimals

### ISSUE THREAD

**Issue by mickaeltr** [adamwdraper/Numeral-js#107]
My customer is asking for the following currency format in Switzerland:

numeral("???").format(12.0) => "CHF 12.-"
numeral("???").format(12.3) => "CHF 12.30"

Is it currently possible? If not, can you think of a pattern that would describe this?
I am willing to spend some time on developing this feature.

**Comment by adamwdraper** [comment]
Closing because of age. Feel free to reopen if you still have the issue.
