### ISSUE TITLE
Rename language to locale

### ISSUE THREAD

**Issue by ragulka** [adamwdraper/Numeral-js#109]
Language should be renamed to locale, because we are not really dealing with languages here. The same language can be used in different countries, but still have different requirements for formatting depending on the location.

This is exactly what locales are for - they are a combination of language and location. The current language system actually already uses locales, but they are called languages, which is wrong and may cause confusion.

**Comment by adis-me** [comment]
@jokeyrhyme 

IETF uses hyphens for Language tags:
`Each language tag is composed of one or more "subtags" separated by hyphens (-). Each subtag is composed of basic Latin letters or digits only.`

So, it should give you `en-US`, `pt-BR` etc..
