### ISSUE TITLE
add space support bewteen thousands

### ISSUE THREAD

**Issue by fabien-h** [adamwdraper/Numeral-js#135]
The 0,0.00 format works fine ; why not having a 0 0.00 format ? :)

**Comment by cwallervand** [comment]
+1 to @fabien-h . 1000000 as 1 000 000 would be nice :)

**Comment by isaac-ramthal-css** [comment]
+1

**Comment by andrewm-theodo** [comment]
Another workaround is:

```
numeral(1000000).format('0,0.00').replace(',',' ')
```

to have 1 000 000.00

**Comment by isaac-ramthal-css** [comment]
In that case unformat won't work.

numeral.languageData().delimiters.thousands = ' ';


seems a better option.

**Comment by choyweston** [comment]
The workaround mentionned by andrewm-theodo is actually : 
    numeral(1000000).format('0,0').replace(/,/g,' ')

**Comment by craPkit** [comment]
For the record: The workaround proposed by @luishdz1010 should operate on `numeral.localeData()` in the current version.
