### ISSUE TITLE
How to change currency?

### ISSUE THREAD

**Issue by gr2m** [adamwdraper/Numeral-js#143]
I don't want to change language, but use € instead of $. `number(1234).format('€0,0.00')` just returns `"1,234.00"`, ignoring the currency symbol. I've looked through the docs and the exisitng issues, but couldn't find any way to just change the currency symbol.

**Comment by johnnytn** [comment]
Any news ? I installed the module, but Just the dolar symbol seems to be working

**Comment by adamwdraper** [comment]
Yes the dollar sign is what tells the format it is a currency that works in the format string.  to change the symbol the locale needs to be changed

**Comment by genne** [comment]
So no support for mixing currencies without changing locale? I.e. no way of expressing €10 and $10 at the same page?

**Comment by eduardoalba** [comment]
@genne Did you find a way of  expressing €10 and $10 at the same page?

**Comment by genne** [comment]
@eduardoalba the only way for me was to exclude the currency from the expression and prepend it manually after formatting it. I.e.

```javascript
let format = "0,0[.]00";
let isNegative = value < 0;
if (isNegative) {
    value = -value;
}
let numberString = currencySymbol + numeral(value).format(format);
if (isNegative) {
    numberString = "-" + numberString;
}
```

**Comment by MaxDonchenko** [comment]
@genne but the currency sign position (before/after the value) also matters

**Comment by genne** [comment]
@goodwin64 yes, I’m handling that manually for now (I only need support for two different locales so it’s quite easy).

**Comment by erajakos** [comment]
I think this is an issue with the version 2.0.6 as well. This might help:

```js
numeral.localeData().currency.symbol = '€'
```
