### ISSUE TITLE
Formatting Scientific Notation with Decimal throws Type Error

### ISSUE THREAD

**Issue by nuclearghost** [adamwdraper/Numeral-js#150]
When attempting to format a number given in scientific notation to a format that contains decimals it throws the following type error with stack trace

```
TypeError: Cannot read property 'length' of undefined
at formatNumber (numeral.js:360:36)
at formatNumeral (numeral.js:75:22)
at Object.numeral.fn.Numeral.format (numeral.js:587:20)
```

The input to reproduce is 

```
numeral("1E+28").format("0.0")
```

This works fine with the following input

```
numeral("1E+28").format("0")
```

This was discovered using  _numeral.js_ v1.5.3 on _Chrome_ 33.0.1750.154 m

**Comment by adamwdraper** [comment]
This is supported but with the format of `1e+28`
