### ISSUE TITLE
Adding extra decimal places to a number when formatting

### ISSUE THREAD

**Issue by jbrockmeyer** [adamwdraper/Numeral-js#154]
Hey,
I'm having an issue where I'm putting in numbers both whole and with decimals and trying to have a universal format to allow the extra decimal points at the end, and am getting extra decimal numbers added to my numbers unexpectedly.

heres a jsfiddle examples (breaks the worst via chrome):

http://jsfiddle.net/SHk9P/42/

**Comment by adamwdraper** [comment]
Fixed
