### ISSUE TITLE
currency symbols mixed up? 

### ISSUE THREAD

**Issue by otmezger** [adamwdraper/Numeral-js#166]
I just downloaded version 1.5.3, and found out that the languages.min.js has the comments mixed up. 

for example: 

function(){var a={delimiters:{thousands:".",decimal:","},abbreviations:{thousand:"k",million:"m",billion:"b",trillion:"t"},ordinal:function(){return"."},currency:{symbol:"CHF"}};"undefined"!=typeof module&&module.exports&&(module.exports=a),"undefined"!=typeof window&&this.numeral&&this.numeral.language&&this.numeral.language("de-ch",a)}(),/*! 
- numeral.js language configuration
- language : German (de) – generally useful in Germany, Austria, Luxembourg, Belgium
- author : Marco Krage : https://github.com/sinky
  */

the comment says: German(de), but the code says this.numera.language("de-ch"). 

the same with uk:

function(){var a={delimiters:{thousands:" ",decimal:","},abbreviations:{thousand:"k",million:"m",billion:"b",trillion:"t"},ordinal:function(){return"."},currency:{symbol:"€"}};"undefined"!=typeof module&&module.exports&&(module.exports=a),"undefined"!=typeof window&&this.numeral&&this.numeral.language&&this.numeral.language("de",a)}(),/*! 
- numeral.js language configuration
- language : english united kingdom (uk)
- author : Dan Ristic : https://github.com/dristic

code says "de", but comment "uk". the values in the code are correct, tho.

**Comment by adamwdraper** [comment]
Fixed.
