### ISSUE TITLE
Support for default currency formats in language files

### ISSUE THREAD

**Issue by apapirovski** [adamwdraper/Numeral-js#17]
The hypothetical scenario would be that you have an app that needs to be able to show a cost of something in various languages/currencies (which a ton of e-commerce sites do). It would be great if we could provide that to the developer rather than having them put a bunch of conditionals in their code so they can add the correct format.

It could then also be used in unformat for greater accuracy when working with the various language-specific currency formats — right now it's pretty inflexible.

Maybe similar to L, LL, LLL, and LLLL in Moment.js it would be something like:

$: $100k, € 500k, 500 tis. Kč, etc.
$$: $500,000, € 500.000, 500 000 Kč, etc.
$$$: $500,000.00, € 500.000,00, 500 000,00 Kč, etc.

Something like that — just quickly threw that together so it can obviously change. Feels like that's an area where Numeral-js could be really useful. Any thoughts? (I would be happy to write the code if there's interest.)

**Comment by adamwdraper** [comment]
This can be achieved with formatting.
