### ISSUE TITLE
Currency placement

### ISSUE THREAD

**Issue by eranimo** [adamwdraper/Numeral-js#184]
It doesn't look like the language files take into account currency symbol placement. In much of the Eurozone, the Euro symbol is placed on the right. I'm using the French language file, and this is the result:

``` javascript
numeral("100").format('$0,0.00')
--> "€100,00"
numeral("10000").format('$0,0.00')
--> "€10 000,00"
```

It should be 100,00 €

See http://userguide.icu-project.org/formatparse for examples of what is expected

**Comment by iArnaud** [comment]
+1

**Comment by zyre91** [comment]
::thumbsup::

**Comment by BostjanPisler** [comment]
+1

**Comment by adamwdraper** [comment]
fixed

**Comment by R1Daneel** [comment]
Is the position of the currency handled automatically by the library  based on the current locale or do I need to specify the position manually? @adamwdraper

**Comment by samdjstevens** [comment]
@adamwdraper Are you open to an extra setting for this in the `currency` object in locales? 

Would be really useful for multi language apps to make setting the right position of the currency symbol configurable in locales rather than implementing custom logic based on the user locale.

**Comment by sesam** [comment]
> fixed

Where and how is this handled? In the master branch, I only find 

```
                    before: format.match(/^([\+|\-|\(|\s|\$]*)/)[0],
                    after: format.match(/([\+|\-|\)|\s|\$]*)$/)[0]
```

which can not correctly handle the case where € is either in front or behind depending on country and language settings.
