### ISSUE TITLE
Optional decimals

### ISSUE THREAD

**Issue by yesman85** [adamwdraper/Numeral-js#186]
Is there a way currently to show optional decimals?

Something like this:

0,0.##

1234 -> 1,234
1234.5 -> 1,234.5
1234.56 -> 1,234.56
1234.567 -> 1,234.57

etc.

**Comment by panzerdp** [comment]
Optional decimals would be really nice to have. Thanks!

**Comment by hartadi** [comment]
try: 0,0.[00]

**Comment by adamwdraper** [comment]
what hartadi said 0,0.[00]

**Comment by stevehanson** [comment]
Not what the OP was looking for, but if anyone else stumbles on this looking for a way to optionally not show cents with currency, `0,0[.]00` worked best for me:

`0,0[.]00`
1.55 => 1.55
1.5 => 1.50
1 => 1

`0,0.[00]`
1.55 => 1.55
1.5 => 1.5
1 => 1
