### ISSUE TITLE
Change the name of the language file portuguese brazil

### ISSUE THREAD

**Issue by newerton** [adamwdraper/Numeral-js#189]
Was having trouble to set the language of origin.
The name of the 'pt-br' language file is wrong.

The correct is 'pt-BR', according to ISO 639-1:2002 standard.
Until browsers identifies language as 'pt-BR'.

**Comment by jamiter** [comment]
There are more languages in this repository with incorrect language codes, like `be-nl`, which should be `nl-BE`.

So +1, but not just for the language you specified.

**Comment by jamiter** [comment]
Hi @adamwdraper, are you planning to update the codes or is there a reason for having them this way? The issue hasn't been resolved yet so I'm just curious why the ticket is being closed.
