### ISSUE TITLE
Default rounding in toFixed as impelmented on MDN

### ISSUE THREAD

**Issue by istrasoft** [adamwdraper/Numeral-js#193]
Hi,

have you considered including the very nice and accurate rounding function provided by the guys from Mozilla instead of the Math.round \* power / power technique which leads as the code comments says to inconsistent floating point rounding ?

Kind regards

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round

**Comment by fsateler** [comment]
The current method is very bad: due to double rounding, formatting certain numbers with large enough precision results in errors:

    numeral(5241340125).format('0.000000000') // returns "5241340124.999999046"

Using the mozilla function (slightly modified) as follows yields the correct result:

	diff --git a/WebApp/Scripts/numeral/numeral.js b/WebApp/Scripts/numeral/numeral.js
	index 9f46ab6..7bbe0ea 100644
	--- a/WebApp/Scripts/numeral/numeral.js
	+++ b/WebApp/Scripts/numeral/numeral.js
	@@ -33,6 +33,25 @@
			 this._value = number;
		 }
	 
	+    function decimalAdjust(round, value, exp) {
	+        // If the exp is undefined or zero...
	+        if (typeof exp === 'undefined' || +exp === 0) {
	+            return round(value);
	+        }
	+        value = +value;
	+        exp = +exp;
	+        // If the value is not a number or the exp is not an integer...
	+        if (isNaN(value) || !(typeof exp === 'number' && exp % 1 === 0)) {
	+            return NaN;
	+        }
	+        // Shift
	+        value = value.toString().split('e');
	+        value = round(+(value[0] + 'e' + (value[1] ? (+value[1] - exp) : -exp)));
	+        // Shift back
	+        value = value.toString().split('e');
	+        return +(value[0] + 'e' + (value[1] ? (+value[1] + exp) : exp));
	+    }
	+
		 /**
		  * Implementation of toFixed() that treats floats more like decimals
		  *
	@@ -46,7 +65,8 @@
				 
			 //roundingFunction = (roundingFunction !== undefined ? roundingFunction : Math.round);
			 // Multiply up by precision, round accurately, then divide and use native toFixed():
	-        output = (roundingFunction(value * power) / power).toFixed(precision);
	+        output = decimalAdjust(roundingFunction, value, -precision).toFixed(precision);
	+        //output =  (roundingFunction(value * power) / power).toFixed(precision);
	 
			 if (optionals) {
				 optionalsRegExp = new RegExp('0{1,' + optionals + '}$');

**Comment by adamwdraper** [comment]
This looks to be a floating point error, which numeral does not attempt to solve
