### ISSUE TITLE
format() on a numeral initialized with Infinity throws TypeError 'length' of undefined

### ISSUE THREAD

**Issue by ACReeser** [adamwdraper/Numeral-js#199]
See this jsfiddle:
http://jsfiddle.net/6whwb8zn/

It's an edge case, as in a perfect world no-one is passing Infinity to numeral, but the error is such that it's impossible to tell that the numeral was created as Infinity.

**Comment by mgodwin** [comment]
:+1:

**Comment by timdorr** [comment]
Actually's it's not really an edge case at all. I'm using it with some Angular bindings so I can do this:

`{{step.clicked_count / step.sent_emails_count || 0 | numeraljs:'0.0%'}}`

If my `step.sent_emails_count` is zero, then it pops an `Infinity` into `format()`. It's already happening a bit in my production app.

**Comment by adamwdraper** [comment]
now returns Infinity
