### ISSUE TITLE
Add support for locales

### ISSUE THREAD

**Issue by llacroix** [adamwdraper/Numeral-js#2]
It shouldn't be that hard to implement. I took your numeral.js files and added some options.

```
numeral.delimiters = {
    thousands: ',',
    decimals: '.'
}
```

For french language, it should be something like that:

```
numeral.delimiters = {
    thousands: ' ',
    decimals: ','
}
```

Replace line 179 by 

```
w = w.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1' + numeral.delimiters.thousands);
```

Replace line 188 by 

```
d = numeral.delimiters.decimals + toFixed(n._n, precision.length).split('.')[1]; 
```

This is a quick fix to add different kind of delimiters. If you're interested to make that lib a bit more complete. I suggest you to take a look at babel.numbers

http://babel.edgewall.org/wiki/ApiDocs/babel.numbers

Having something similar to that in javascript would be simply awesome.

**Comment by denys-kostenko** [comment]
Hello.

What about to support language format as in http://cldr.unicode.org/index/cldr-spec/json ?
