### ISSUE TITLE
zeroFormat ignored for currency and percentage

### ISSUE THREAD

**Issue by drglitch** [adamwdraper/Numeral-js#204]
When using zeroFormat with currency or percentages, its behavior is inconsistent with numerics, e.g. format(0.00%) with zeroFormat == '-' is formatted as '-%' instead of expected '-'.

Similarly, zero currency formats come out as '-$'

Is this behavior by design or a bug? (i can see arguments for both, but would consider this a bug).
Will gladly submit a pull request to normalize behavior if needed!

**Comment by harrymckee** [comment]
similarly, setting zeroFormat = '' causes number(0).format('$0,0.00') to return '$' instead of ''

**Comment by adamwdraper** [comment]
fixed
