### ISSUE TITLE
Passing undefined returns 0

### ISSUE THREAD

**Issue by ghost** [adamwdraper/Numeral-js#238]
We found that passing undefined to the number function will cause it to return 0.

```
$ node
> require("numeral")(undefined).value();
0
```

**Comment by carbontwelve** [comment]
What would you expect it to return?

**Comment by Soliah** [comment]
This is problem when trying to deal with `undefined` in a custom formatter, as we lose the information once we're inside the `format` function that the value was originally `undefined`. Is there an API we can use inside a formatter to get the original value?

**Comment by marcelh-gh** [comment]
@adamwdraper may I ask why this was closed?
I don't see where the value of `0 `makes sense for `undefined `as input.
I would either expect this to follow the setting via `numeral.nullFormat()` or the addition of a new `numeral.undefinedFormat() `
In my personal opinion a default of "N/A" would make sense.

**Comment by carbontwelve** [comment]
I'd personally expect it to return `NaN`
