### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by dandean** [adamwdraper/Numeral-js#242]
Hello!

Is this project still being actively maintained? Not a criticism or critique, just wondering while deciding whether or not to use this project as a dep. I've noticed that there are some forks with much more commit activity. Should one of those be considered the main fork now?

Thank you for your time and contributions!

**Comment by ttamminen** [comment]
+1 I am wondering the same thing. The project overall looks promising, but amount of issues and open pull requests makes me skeptical.

**Comment by MadMG** [comment]
+1 Alive would be nice. @adamwdraper  There are many useful open pull requests!

**Comment by pawelhenek** [comment]
@adamwdraper maybe would you like to delete the responsibility for the project to someone else? or share the administration permissions?

**Comment by jamiter** [comment]
+1 This project is very good, but needs a maintainer...

**Comment by Semigradsky** [comment]
This fork looks good: https://github.com/foretagsplatsen/Numeral-js

**Comment by jamiter** [comment]
@Semigradsky, yes, it does look good. Maybe we can focus on that one and maybe someday have @adamwdraper merge it. There are a lot of forks out there and issues here, so we can concentrate on one, that would be great.

**Comment by LukaszKrawczyk** [comment]
:+1:

**Comment by dandean** [comment]
One thing that makes this tough, is that it doesn't handle publishing to npm. An alternative would be to rename the fork and publish under a new name.

**Comment by srph** [comment]
Anybody interested in forking this library -- a friendly fork -- and publish this under a new name?

**Comment by srph** [comment]
Mind if we continue the discussion on https://github.com/foretagsplatsen/Numeral-js/issues/10#issuecomment-87290853 (a [fork](https://github.com/foretagsplatsen/Numeral-js) by [foretagsplatsen](https://github.com/foretagsplatsen)) ?

**Comment by BenjaminVanRyseghem** [comment]
I am working a Företagsplatsen, and more or less in charge of this fork.

I would love people to contribute to it. I already opened a PR to this repo, but it looks like the project is almost dead.

If some people are willing to join forces, we could make it together (and since the code is still pretty close, I am pretty sure that a lot of PRs still applies)

**Comment by uniphil** [comment]
FYI: Work on the Företagsplatsen fork has moved to [numbro](https://github.com/foretagsplatsen/numbro), with many open issues here already fixed, and pull requests from here are being merged.

I'm currently working on documenting all the improvements and changes to make it easier to switch, but there is already a release published on `npm`, `bower`, and `ender`. It's ready now, and improving quickly!

**Comment by dandean** [comment]
:metal:

**Comment by A----** [comment]
That fork has its own repository now: https://github.com/foretagsplatsen/numbro/tree/master

**Comment by dandv** [comment]
We want to package this library for Meteor and are wondering the same thing - is it maintained? If not, which fork is the most promising one going forward?

**Comment by srph** [comment]
Numbro is a well maintained fork.

**Comment by jamiter** [comment]
@dandv, good thing you want to package this for Meteor. I also strongly advice to use numbro instead. Same code, well maintained. Already has quite some improvements over numeral.

You can find it here: https://github.com/foretagsplatsen/numbro

**Comment by BenjaminVanRyseghem** [comment]
@dandv we will be glad to be packaged for meteor :smile:

**Comment by dandv** [comment]
@splendido, see @jamiter's comment.

**Comment by thisguychris** [comment]
looks like this project started to have movement again! 🎉

**Comment by adamwdraper** [comment]
Yes it is.

**Comment by BenjaminVanRyseghem** [comment]
@adamwdraper we made some progress on [numbro](https://github.com/foretagsplatsen/numbro) (including merging many PR from here).

Maybe we could join the effort somehow?

**Comment by jamiter** [comment]
@adamwdraper, what is your opinion on a merge with numbro? This package has been silent for a long time and the progress made in numbro would be very welcome. No need for competition if both do the exact same job. Any response is welcome.

**Comment by mbonaci** [comment]
Can't believe a guy would desert this, not put some kind of info on top of README and not give someone admin rights.
There are issues still opened daily and even PRs submitted.
