### ISSUE TITLE
Support for handling null and zero differently

### ISSUE THREAD

**Issue by wrschneider** [adamwdraper/Numeral-js#256]
Right now numeral supports a zeroFormat.  What I'd like is the ability to leave zero alone but print N/A or "--" for nulls.

Unfortunately nulls are coerced to zeros on creation (`numeral(null).format() === "0"`)

Would it be reasonable to leave nulls alone, so they can be formatted differently?

**Comment by rwbaskette** [comment]
bump. i'm in the middle of a project that should output nothing for null fields in a large datatable.

formatting null yielding null makes sense to me. you can then do a `(numeral(null_val).format('0.00') || 'N/A')`

**Comment by Wildhoney** [comment]
I've created a PR, but there seems to be something peculiar happening with the PR.

**Comment by adamwdraper** [comment]
Done!

**Comment by Wildhoney** [comment]
Genius! Thanks.
