### ISSUE TITLE
Precision error

### ISSUE THREAD

**Issue by maximilianschmitt** [adamwdraper/Numeral-js#260]
Hi,

I really wanted to use numeral to do some financial calculations but there seem to be some precision errors. Like this one:

```js
> numeral('-5.1755').add(numeral('-0.2'))
{ [Number: -5.375500000000001] _value: -5.375500000000001 }
```

I expected the result to be `-5.3755`.

Is this expected behaviour, a bug or am I doing something wrong?

Thanks for your help!

**Comment by ttamminen** [comment]
Correct me if I am wrong, but JavaScript doesn't have a decimal datatype which is normally used for human invented things, such as currency.

NumeralJS can't solve this issue as it is more focused on formatting the currency than actual calculation.

Check this StackOverflow answer for various solutions:
http://stackoverflow.com/a/3439981/253793

**Comment by maximilianschmitt** [comment]
Thanks for the reply. I wasn't aware that NumeralJS was focussed on the formatting. I've been using this to calculate values more accurately: https://github.com/MikeMcl/bignumber.js/
