### ISSUE TITLE
Abbreviated Numbers rounding issue

### ISSUE THREAD

**Issue by davidandrus** [adamwdraper/Numeral-js#264]
When using the format string '0.0a' numbers in the interval [999950,  999999] show as 1000.0K when they should show 1.0M.

See: http://codepen.io/skatan/pen/EjjLGr for an example

**Comment by jamiter** [comment]
Hi, this repository is no longer maintained. You can get an improved version here: https://github.com/foretagsplatsen/numbro. That one is still maintained and you can report your issues there.

**Comment by adamwdraper** [comment]
going to address as duplicate of #283
