### ISSUE TITLE
Allow for large numbers separated by spaces

### ISSUE THREAD

**Issue by frozeman** [adamwdraper/Numeral-js#265]
Its common in germany to separate 1000th by spaces e.g.  `100 000.00`

Currently `0 0.[00` will lead to `100000.00`.

It would also be nice to allow international separation of decimal points like `100.00` instead of `100,00`

**Comment by shershen08** [comment]
+1

**Comment by olivierlesnicki** [comment]
+1

**Comment by arcontact** [comment]
+1

**Comment by phildionne** [comment]
+1

**Comment by andrzey** [comment]
+1

**Comment by adamwdraper** [comment]
This can be solved by creating a custom locale, like https://github.com/adamwdraper/Numeral-js/blob/master/locales/de.js
