### ISSUE TITLE
Millions abbreviation should default to mm

### ISSUE THREAD

**Issue by thomblake** [adamwdraper/Numeral-js#269]
See http://en.wikipedia.org/wiki/Million

'm' is a confusing abbreviation because in some contexts it means 'thousand', so 'mm' is preferred.

**Comment by chrisnicola** [comment]
The standard in [The Economist](http://www.economist.com/style-guide/abbreviations) is capital "M". If that matters at all.

**Comment by chrisnicola** [comment]
As does Yahoo Finance: https://ca.finance.yahoo.com/q?s=XEF.TO

**Comment by thomblake** [comment]
Nice link to an actual standard.  Feel free to close this.

**Comment by aalhaimi** [comment]
Pretty old issue, but have to agree... it should be capitalized.
