### ISSUE TITLE
Binary prefix

### ISSUE THREAD

**Issue by yukulele** [adamwdraper/Numeral-js#275]
Byte notation should use binary prefix (Kio, Mio, Gio, Tio, ...):
https://en.wikipedia.org/wiki/Octet_%28computing%29#Unit_multiples

**Comment by jamiter** [comment]
Hi, this repository is no longer maintained. You can get an improved version here: https://github.com/foretagsplatsen/numbro. That one is still maintained and you can report your issues there.

**Comment by adamwdraper** [comment]
Done
