### ISSUE TITLE
Rounding happens before signed check

### ISSUE THREAD

**Issue by MicHuizinga** [adamwdraper/Numeral-js#279]
numeral(0.04).format("+0.0")
"+0.0"

numeral(-0.04).format("+0.0")
"+0.0"
should be "-0.0"

**Comment by adamwdraper** [comment]
I don't think there is really such a thing as -0.0 so +0.0 is expected  me.

**Comment by MicHuizinga** [comment]
Well, in your reasoning there would also be no such thing as +0.0

If you're going to display the sign at all, it should really match the sign of the original number. Just because we're rounding a value, doesn't mean the other digits weren't significant! We're just formatting for display, to make the numbers fit nicely in a table.

It's really weird to have the number -0.04 displayed as +0.0 especially when the user knows that all numbers in a table are rounded and there's a significant difference in meaning between positive and negative numbers, which is the reason to explicitly display the sign.
In my case I was showing growth percentages, and your lib would format a negative growth of -0.04% as +0.0%, falsely suggesting that there was no negative growth at all.
This is probably great for politicians, but the rest of the world likes their data to be truthful :)

**Comment by Drumstix42** [comment]
If you do formatting in Excel for money, and you turn on the coloring features, or parenthesis, you will indeed see red/parens around numbers rounded to zero, when they were originally a negative number.
