### ISSUE TITLE
Multiply floating point errors

### ISSUE THREAD

**Issue by lededje** [adamwdraper/Numeral-js#286]
`numeral(64.43).multiply(100);` // 6443.000000000001

I know this is a floating point issue but I thought that is what this library was meant to sort out.

**Comment by jamiter** [comment]
Hi, this repository is no longer maintained. You can get an improved version here: https://github.com/foretagsplatsen/numbro. That one is still maintained and you can report your issues there.

**Comment by adamwdraper** [comment]
This library is not meant to address floating point errors specifically, but in this case it is now fixed!
