### ISSUE TITLE
Formatting Infinity With Decimals Throws a Type Error

### ISSUE THREAD

**Issue by Abarrowman** [adamwdraper/Numeral-js#288]
A piece of code I was writing had a bug and was returning infinities and I discovered that numeral fails when trying to format infinity to have decimals, specifically:

numeral(Infinity).format("00.0"); //throws TypeError: Cannot read property 'length' of undefined

The minimal failing case is the following:
numeral(Infinity).format(".0");

**Comment by jamiter** [comment]
Hi, this repository is no longer maintained. You can get an improved version here: https://github.com/foretagsplatsen/numbro. That one is still maintained and you can report your issues there.

**Comment by adamwdraper** [comment]
Fixed
