### ISSUE TITLE
support for hexadecimal?

### ISSUE THREAD

**Issue by mqchau** [adamwdraper/Numeral-js#294]
Hi,
I'm using python Bokeh and it's using Numeral.js to do number formatting. I'm looking for a way to display my unsigned integer as hexadecimal string but I can't find it. Could you please add support for hexadecimal output?

Thank you.
Quan.

**Comment by jamiter** [comment]
Hi, this repository is no longer maintained. You can get an improved version here: https://github.com/foretagsplatsen/numbro. That one is still maintained and you can report your issues there.

**Comment by mqchau** [comment]
Thanks, I'll close this then.
