### ISSUE TITLE
numeral() instanceof numeral returns false

### ISSUE THREAD

**Issue by nsbawden** [adamwdraper/Numeral-js#297]
Can it made so that the javascript standard way of finding out what an object **IS** works with numeral? With the latest version using `numeral(1) instanceof numeral` returns `false`.

I can put `numeral.prototype = numeral.fn` at the beginning of my code and then `numeral(1) instanceof numeral` returns `true` and everything seems fine in the ways I am using numeral. However, there may be some case where this does not work so it would be real handy to have this ability integrated into the library by a professional to ease our testing when a numeral is a numeral, if it is as simple to do as it appears.

Thanks in advance,
dAc

**Comment by adamwdraper** [comment]
use `numeral.isNumeral(numeral(1));`.  Thanks
