### ISSUE TITLE
language `es-ES` overwrites `es`

### ISSUE THREAD

**Issue by splendido** [adamwdraper/Numeral-js#298]
See [this line](https://github.com/adamwdraper/Numeral-js/blob/master/languages/es-ES.js#L37) which is exactly like [the one](https://github.com/adamwdraper/Numeral-js/blob/master/languages/es.js#L37) used for `es`.
Obviously the same is true within the unified languages file at [this line](https://github.com/adamwdraper/Numeral-js/blob/develop/languages.js#L282)

I guess it should be:

``` javascript
this.numeral.language('es-ES', language);
```

At the moment, version 1.5.3, if you call

``` javascript
numeral.language('es-ES'):
```

you get an error saying `Unknown language : es-ES`

**Comment by qborreda** [comment]
+1

**Comment by sandervanhooft** [comment]
+1 for nl-NL. Did you find a solution?

**Comment by adamwdraper** [comment]
all files names are standardized as lowercase in 2.0 so this should be fixed.
