### ISSUE TITLE
leading zeros??

### ISSUE THREAD

**Issue by sdwarwick** [adamwdraper/Numeral-js#300]
Hi - Is there any way to have this package format for leading zeros?

numeral( 1 ).format('zzzz') =>  "0001"

**Comment by morficus** [comment]
+1

**Comment by hhamilto** [comment]
+1

**Comment by hunt** [comment]
+1

**Comment by cartas510** [comment]
+1

**Comment by metalik** [comment]
+1

**Comment by g-holmes** [comment]
+1

**Comment by datenstau** [comment]
+1

**Comment by donpedro** [comment]
This is done on numbro fork (numbrojs.com):

`numbro(300).format("00000") // "00300"`

**Comment by joelpresence** [comment]
Could we merge this into master please?  :-)  Not having this a show stopper for my use case ... I just want sprintf.  😜

**Comment by joelpresence** [comment]
And I'm willing to help with that, if you need me to ... I'm not just trying to whine.

**Comment by Eric24** [comment]
+1

PS - I vote for the syntax of numeral(300).format('00000) => "00300". It seems more consistent with the current numeral.js design.

**Comment by erichsu** [comment]
+1

**Comment by vivekkhandelwal** [comment]
+1

**Comment by TheFabio** [comment]
+1

**Comment by adamwdraper** [comment]
Will be added in 2.0.5
