### ISSUE TITLE
Help in format (-#,##0)

### ISSUE THREAD

**Issue by marlonmleite** [adamwdraper/Numeral-js#305]
Hello,

I would like to format my numbers when negative for the following format:

Format:
(-#,##0)

Example 1:
Input: 1000 | Output: 1.000

Example 2:
Input: -1000 | Output: (-1.000)

It is possible?

**Comment by Bertuzb** [comment]
numeral(input).format('0.000')

negative numbers should work as intended

fiddle: https://jsfiddle.net/38fvk4ra/

**Comment by marlonmleite** [comment]
Hello,

Expected to present: (-2.234)
Including the brackets ().

not work in fiddle: https://jsfiddle.net/38fvk4ra/1/

**Comment by Bertuzb** [comment]
so the brackets should only be applied to negative numbers? id suggest adding them after format then because its such a random usecase

**Comment by adamwdraper** [comment]
Numeral supports a - sign or ()'s for negative numbers, not both.  do as bertuzb suggested and add the brackets afterwards.  Thanks
