### ISSUE TITLE
Transfer numeral js ownership

### ISSUE THREAD

**Issue by Bertuzb** [adamwdraper/Numeral-js#306]
Why isnt this repository transfered to someone who is willing to  maintain this?

**Comment by tujoworker** [comment]
+1 I agree. There are so manny pull requests. This should definitely be maintained. Are You @Bertuzb willing to do this?

**Comment by Bertuzb** [comment]
I am willing to do this (experienced javascript developer) but its not my call

**Comment by MeTaNoV** [comment]
check out a maintened and renamed fork: https://github.com/foretagsplatsen/numbro

**Comment by adamwdraper** [comment]
I'm working on this project again.  If I run out of time again I'll make sure to get someone to maintain it again.
