### ISSUE TITLE
Big number and long format issue

### ISSUE THREAD

**Issue by fredericoschardong** [adamwdraper/Numeral-js#308]
Apparently numeral.js doesn't like big numbers and long format:

```
numeral('1231323211231.123').format('0.[0000000000]')
"1231323211231.123046875"
```

I would expect this result:

```
"1231323211231.123"
```

https://jsfiddle.net/1c242d5f/1/

**Comment by adamwdraper** [comment]
This looks fixed in the latest version

**Comment by hanbar** [comment]
I don't think so... please try numeral('123456789123456789').format('0,0'));
You will get 123,456,789,123,456,784 so when you have more than 17 digits, every additional digit is transformed somehow

**Comment by hanbar** [comment]
I don't think so... please try
`numeral('123456789123456789').format('0,0'));`
You will get 123,456,789,123,456,784 so when you have more than 17 digits, every additional digit is transformed somehow

**Comment by jsolman** [comment]
numbers in javascript only support double precision (you don't get more than 16 significant digits)
