### ISSUE TITLE
format % is incorrect

### ISSUE THREAD

**Issue by deksoke** [adamwdraper/Numeral-js#309]
i found a problem about format('0.0%');

i use numeral(89.93).format('0.0%'); //correct answer = 83.93%
but output is >> 8993.00%
please fix this bug.

i enjoy with your work very much ^^
thank you

**Comment by mcallan83** [comment]
This is actually not a bug. The percent sign is equivalent to "divided by 100". In other words, 50% = 50/100 = .50. So 1% is actually .01 in decimal form, and 100% is 1.00.

To represent 89.93%, you would need a decimal value of .8993.

**Comment by deksoke** [comment]
thank you for reply. mcallan83
