### ISSUE TITLE
bytes to kilobytes, megabytes etc

### ISSUE THREAD

**Issue by markve-sa** [adamwdraper/Numeral-js#312]
The conversion is not in line with the International System of Units.

Currently Numeral-js converts 1024 bytes to 1 Kilobyte (kB) but 1024 bytes has officially been a Kibibyte (KiB) since 1998 

1000B = kB (kilobyte)
1000000 =    MB (megabyte)
1000000000B = GB     (gigabyte)

1024B = KiB (kibibyte) 
1048576B = MiB (mebibyte)
1073741824 = GiB (gibibyte)

Most operating systems file managers have been updated to report the size as defined in the standard.

Is there any chance that Numeral-js will be updated ?

**Comment by joaomvfsantos** [comment]
+1

**Comment by sirianni** [comment]
+1

**Comment by jeancornic** [comment]
+1
See https://en.wikipedia.org/wiki/Mebibyte for example.

**Comment by leeway23** [comment]
Hi All, 

For your parameter e.g. number of bytes of memory used called ‘avgRSS’ one can create a scripted field in Kibana with the following formula: 

name of the scripted field: avgRSS_main_reco 
Type : Bytes
Script: doc[‘avgRSS'].value \* pow(1.024, floor(ln(doc['avgRSS'].value)/ln(1000)))

This corrects for the wrong binary conversion factor finally using decimal one in line with the decimal unit labels. 

It carries with it the inconvenience, that one has to be alert in case Kibana fixes the issue in the future. but as far as I have heard, this is not going to happen anytime soon (problem located in one of the upstream libraries). Also, Kibana applies this correction factor per-document-value, i.e. it will not show a correct number after aggregation ! Another option, less elegant, but functional is : 

<img width="750" alt="screen shot 2018-04-09 at 17 36 48" src="https://user-images.githubusercontent.com/17620216/38507553-21b1d96a-3c1d-11e8-9a42-013adec80164.png">
 

Cheers, 
J.

PS: for general n-core jobs e.g.:  (doc[‘avgRSS'].value/doc['ncores'].value) \* pow(1.024, ln(doc['avgRSS'].value/doc['ncores'].value)/ln(1000))

**Comment by adamwdraper** [comment]
1.5.6 added a new format you can use `ib` to display kibibytes.  2.0.0 will finish that conversion and convert kilobyte to be calculated using 1000 instead of 1024.

**Comment by spe-shun** [comment]
![image](https://user-images.githubusercontent.com/18157400/162981636-f48116ba-7621-4548-9e8b-1632aa8dc161.png)
http://numeraljs.com/#format 1024 -> 0b -> 1 KB has not change yet
