### ISSUE TITLE
Thousand separator with percents

### ISSUE THREAD

**Issue by XavierDupessey** [adamwdraper/Numeral-js#318]
Hello,

I got a problem with the percent format on bug numbers: `numeral(10).format('%')` returns `"1000%"` whereas `"1,000%"` (with the comma) is expected.

Or maybe I missed something?

Thanks in advance,
Xavier

**Comment by arjshiv** [comment]
Use the format string along with the % sign

```js
numeral(40).format('0,0%')
//=> "4,000%"
```
