### ISSUE TITLE
Round issue when decimal number ends with 25

### ISSUE THREAD

**Issue by singhvivek2503** [adamwdraper/Numeral-js#320]
I get rounding issue when i format decimal number that ends with 25
Eg:
Input: numeral(4515.525).format('0,0.00') 
Output: 4,515.52
Expected: 4,515.53
Please advise.

**Comment by kayneb** [comment]
Additionally:
Input numeral(0.145).format('0%')
Output: 14%
Expected: 15%

I can't seem to reproduce this for other xx5s, i.e.

Input numeral(0.155).format('0%')
Output: 16%
Expected: 16%

**Comment by a1duffy** [comment]
I found a similar issue with the numbers in this http://jsfiddle.net/a1duf/07ku897p/
