### ISSUE TITLE
NO LONGER MAINTAINED - USE NUMBRO

### ISSUE THREAD

**Issue by jhabdas** [adamwdraper/Numeral-js#323]
I discovered a fork of this library which is more actively maintained: http://numbrojs.com/

![screen shot 2016-03-18 at 1 54 19 pm](https://cloud.githubusercontent.com/assets/440298/13888728/f4d8f00c-ed10-11e5-8633-d61d9d3252d1.png)

@adamwdraper Please update the `README` if you can to add a deprecation notice for this library and point to Numbro instead. I'd submit a PR, but it's fairly clear it won't be merged.

**Comment by MeTaNoV** [comment]
already the case for me! :)

**Comment by vanthome** [comment]
@adamwdraper why the hell can't you put a note on the project page that it's no longer maintained?!

**Comment by jhabdas** [comment]
Even better than Numero is the toLocaleString method to save a dependency while affording dynamic internationalized currency formatting without much fuss.
