### ISSUE TITLE
Can't run tests:  "Error: No such module: evals"

### ISSUE THREAD

**Issue by adc-gsandell** [adamwdraper/Numeral-js#336]
I've tried installing Numeral with Node 5.3.0 and v0.11.16

**Comment by adc-gsandell** [comment]
Fixed it with ```npm update grunt-contrib-nodeunit -S```

**Comment by Wildhoney** [comment]
Didn't work for me &mdash; use `nodeunit` directly.

```
npm i nodeunit -g
odeunit tests/**/*.js
```
