### ISSUE TITLE
apostrophe for thousands

### ISSUE THREAD

**Issue by Remo** [adamwdraper/Numeral-js#338]
Two small countries, Switzerland and Liechtenstein, are often using apostrophe for thousands. See https://en.wikipedia.org/wiki/Decimal_mark

I would have expected this to work:

```
numeral(1230).format("0'0.00") // = 1'230.00
```

Any pointers to get me in the right direction?

**Comment by zamudpoe** [comment]
Hi Remo!, I share my coniguration for Mexico , you can modify it for your country , I hope this could be useful for You and others, regards.

**// Mexico format**
      numeral.language('MX', {
        delimiters: {
            thousands: '\'',   // Here is the apostrophe.
            decimal  : '.'
        },
        abbreviations: {
            thousand: 'K',
            million : 'M',
            billion : 'B',
            trillion: 'T'
        },
        ordinal : function (number) {
            return number === 1 ? 'er' : 'ème';
        },
        currency: {
            symbol: '$'
        }
      });

      numeral.language('MX');

**Comment by Remo** [comment]
@zamudpoe  thanks, but I already switched to numbro as numeraljs seems to be dead. My PR has already been merged there https://github.com/foretagsplatsen/numbro/pull/206

**Comment by Remo** [comment]
@adamwdraper this is still wrong in your repo.

**Comment by adamwdraper** [comment]
If you load a locale with an apostrophe as the thousands separator then use `numeral(1230).format("0,0.00")` you will get the desired output.  The ',' in the format string means  thousands separator for the current language

**Comment by Remo** [comment]
yes, but the locale is wrong, see here https://github.com/foretagsplatsen/numbro/pull/206/files
