### ISSUE TITLE
I get rounding issue when I try to format interger

### ISSUE THREAD

**Issue by zamudpoe** [adamwdraper/Numeral-js#343]
**Hi everyone!**, I need help to solve this issue!

I get rounding issue when I try to format interger  , I don't want get rounded the integer numbers... I need help to achieve to solve this issue.

**Example** :

**Input**: _numeral(5989432.678).format('0,0.00 a')_
**Output**: _5.99 m_
**Expected**: _5,98.68_

By the way it is a wonderful library , but with this ussue solveed could be even much better.

¿Anyone can show me how it is possible to solve this issue?

**best regards**
**Engelbert**

**Comment by adamwdraper** [comment]
The output is exactly as expected.  Using the `a` it will show an abbreviation in this case million, and it is giving you two decimals.
