### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined(…) when formatting NaN

### ISSUE THREAD

**Issue by yarindekel** [adamwdraper/Numeral-js#345]
The following code line is throwing an error when d is NaN (formatNumber function):  
`if (d.split('.')[1].length)`

TypeError: Cannot read property 'length' of undefined(…) TypeError: Cannot read property 'length' of undefined

Thrown here: https://github.com/adamwdraper/Numeral-js/blob/master/numeral.js#L360

**Comment by yarindekel** [comment]
Fixed it by adding the following check
```
 if (+d === +d) { // since numeral is not supporting NaN, added a check
                    if (d.split('.')[1].length) {
                        d = languages[currentLanguage].delimiters.decimal + d.split('.')[1];
                    } else {
                        d = '';
                    }
                } else {
                    d = '';
                }
```

**Comment by adamwdraper** [comment]
This should now been fixed as NaN is handled as 0 when formatting numbers.
