### ISSUE TITLE
Formatting thousands to k 

### ISSUE THREAD

**Issue by pramodsvidyarthi** [adamwdraper/Numeral-js#351]
when formatting a number to show as 1k, 2k as such when the number is less than 1000 representing the same as 0.5 or 0.6k.

**Comment by KalisaFalzone** [comment]
Also interested in this feature

**Comment by adamwdraper** [comment]
You can already force an abbreviation by using a format like `0.0aK`.  Note in the upcoming 2.0 release it will be `0.0ak`.
