### ISSUE TITLE
numeral(99998000000000.03).format('0,000.00'), but it return 99,998,000,000,000.05

### ISSUE THREAD

**Issue by slonghorn** [adamwdraper/Numeral-js#357]
numeral(99998000000000.03).format('0,000.00') but it return 99,998,000,000,000.05

**Comment by adamwdraper** [comment]
This is caused by a floating point error with such a large number and unfortunately not a problem this library tries to solve.

**Comment by slonghorn** [comment]
but 99998000000000.03.toFixed(2) reutrns 99998000000000.03
