### ISSUE TITLE
kilobyte vs kibibyte

### ISSUE THREAD

**Issue by pcnate** [adamwdraper/Numeral-js#37]
Would be great if there was a distinction between the two as per current standards.

http://en.wikipedia.org/wiki/Kibibyte

**Comment by clayzermk1** [comment]
Excuse me @pcnate, why was this closed? Did this get fixed in numeral.js?

**Comment by pcnate** [comment]
My bad, I thought this was a stale issue.

**Comment by adamwdraper** [comment]
Done
