### ISSUE TITLE
Passing null values previously worked now throws an exception

### ISSUE THREAD

**Issue by esvinson** [adamwdraper/Numeral-js#377]
From 1.5.3 to 1.5.4 there is a breaking change where if you pass a null value it now throws a `Cannot read property 'toString' of null` error

Adding a test for [0, null, '0'] in tests/numeral/format.js results in the following on 1.5.4.  This test passes on 1.5.3.

``` 1) Format Numbers should format to a number:
     TypeError: Cannot read property 'toString' of null
    at formatNumber (numeral.js:389:22)
    at formatNumeral (numeral.js:94:22)
    at Object.format (numeral.js:725:20)
    at Context.<anonymous> (tests/numeral/format.js:92:45)```

**Comment by cesarandreu** [comment]
This is a breaking change :(. It used to return 0.

**Comment by caldwecr** [comment]
Why... why
why


q.q

**Comment by cidylle** [comment]
This breaks my code too :(

**Comment by adamwdraper** [comment]
Thanks.  I think there are a couple breaking changes that I'll patch up and release in a 1.5.6.

**Comment by adamwdraper** [comment]
Take a look at the latest on the `develop` branch.  there is a `1.5.6` version of numeral.  Can you confirm this fixes your issue?  Thanks for the help.

**Comment by esvinson** [comment]
Looks good to me. :+1:
