### ISSUE TITLE
1.5.4 introduces breaking changes

### ISSUE THREAD

**Issue by dknutsen** [adamwdraper/Numeral-js#382]
1.5.4 introduces breaking changes, specifically (I believe) [this line](https://github.com/adamwdraper/Numeral-js/pull/376/commits/6044912dca021412dc1f35dae7ddac1023b4e9e5#diff-9fe609f0dd91fad8d4dca28cc0b0a873L404) which no longer converts a string input to a Number. This means that `numeral("1234").value()` and `numeral(1234).value()` used to be equivalent but no longer are. This just broke our app in a couple places (we were using "~1.5.3" in bower). 

Here is [a 1.5.3 fiddle](http://jsfiddle.net/nc4gkypm/) and [a 1.5.4 fiddle](http://jsfiddle.net/t5a9afu1/) demonstrating the difference.

I'm not sure if the consequences of this change were intentional but at minimum I think it breaks semver convention. It also means, though, that the 'value' method no longer always returns a Number, which is what I would expect based on the docs.

**Comment by adamwdraper** [comment]
Thanks.  I think there are a couple breaking changes that I'll patch up and release in a 1.5.6.

**Comment by adamwdraper** [comment]
Take a look at the latest on the `develop` branch.  there is a `1.5.6` version of numeral.  Can you confirm this fixes your issue?  Thanks for the help.

**Comment by dknutsen** [comment]
@adamwdraper just tested, looks good to me 👍 thanks!
