### ISSUE TITLE
Module cannot be resolved in webpack (also using TypeScript)

### ISSUE THREAD

**Issue by Anupheaus** [adamwdraper/Numeral-js#402]
Hi, I'm using webpack and TypeScript in my project and I've just added your package to my project.  I've downloaded the typings file and I've got Visual Studio and TS to recognise that the module is there.  Unfortunately, when I run webpack on it, it complains that it cannot resolve module "numeral".  My import statement is:

    import * as numeral from "numeral";

and this works in the IDE (i.e. no errors).  I've checked the `node_modules` directory and `numeraljs` is there and there is a file called `numeral.js` in that folder.  But I have noticed that there is no `lib` directory - I'm not sure that is needed, but I seemed to remember that webpack resolves modules by looking in `node_modules/<name>/lib/index.js`, but I could be wrong about that.

Any ideas what I am doing wrong or what I could try please?

**Comment by adamwdraper** [comment]
I don't know enough about webpack or Typescript to help you unfortunately.  Maybe post this on stackoverflow?

**Comment by SpainTrain** [comment]
#403 describes the root issue with webpack

**Comment by adamwdraper** [comment]
Is fixed with 2.0.1.  Thanks

**Comment by matheo** [comment]
@SpainTrain could you please tell me how to make numeral.js work with Rollup?
`rollup-plugin-commonjs` plugin's namedExports or shomething like that?
