### ISSUE TITLE
Module (v2.0.0) doesn't work with webpack

### ISSUE THREAD

**Issue by ulfryk** [adamwdraper/Numeral-js#403]
And it's due to this expression:

```javascript
var numeral = typeof window !== 'undefined' ? this.numeral : require('../numeral')
```

` typeof window !== 'undefined'` returns `true` but there is no `this.numeral` (as there should not be any because WebPack like browserify bases on module systems - not global window object).

To make it work it needs a little change like:

```javascript
typeof window !== 'undefined' && window.numeral ? window.numeral…
```

Or change this condition to check for module systems?

Should look somehow like:
```javascript
(typeof module !== 'undefined' && module.exports) || (typeof define === 'function' && define.amd) ? require('../numeral') : this.numeral
```

**Comment by adamwdraper** [comment]
Is fixed with 2.0.1.  Thanks
