### ISSUE TITLE
es6 will probably break node < 6.5

### ISSUE THREAD

**Issue by leider** [adamwdraper/Numeral-js#412]
You could prevent that if you add the older node versions to you travis file or state clearly that you require the new version.

Reason: `import` does not work for node v6 or earlier

**Comment by adamwdraper** [comment]
If you'll notice node "4" is part of travis.  I am aware that import will not work, I was using a babel plugin that was available), and i believe i will have to create a new babel plugin for a format like this: https://github.com/umdjs/umd/blob/master/templates/returnExportsGlobal.js

**Comment by leider** [comment]
I see. Maybe you should focus on fixing your library first. See #411 :)
