### ISSUE TITLE
TypeError: Cannot read property 'delimiters' of undefined     

### ISSUE THREAD

**Issue by highfeed** [adamwdraper/Numeral-js#415]
TypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormatTypeError: Cannot read property 'delimiters' of undefined
    at numberToFormat

**Comment by highfeed** [comment]
numeral.locale('fr');

**Comment by darkkean** [comment]
I am also getting the same error.

My code is:

```
let number = 10000000.99;
numeral.locale('en-gb');
console.log(numeral(number).format('$ 0,0'));
```

**Error:** `ORIGINAL EXCEPTION: Cannot read property 'delimiters' of undefined`

If I removed the locale config:

```
let number = 10000000.99;
//numeral.locale('en-gb');
console.log(numeral(number).format('$ 0,0'));
```

Code runs and console shows:

`$ 10,000,001`

**Comment by darkkean** [comment]
Ok this is a typescript error, as I am using numeral-js with Angular 2.

It seems that the typings configuration for numeral-js [here](https://github.com/vbortone/DefinitelyTyped/tree/master/numeral) is outdated as it cannot see `locale.delimiters` object.

What I did is to manually `numeral.register` a locale in the constructor (eg: en-gb). Then set the `numeral.locale` there.

```
constructor() {
    numeral.register('locale', 'en-gb', {
        delimiters: {
            thousands: ',',
            decimal: '.'
        },
        abbreviations: {
            thousand: 'k',
            million: 'm',
            billion: 'b',
            trillion: 't'
        },
        ordinal: function (number) {
            var b = number % 10;
            return (~~ (number % 100 / 10) === 1) ? 'th' :
                (b === 1) ? 'st' :
                (b === 2) ? 'nd' :
                (b === 3) ? 'rd' : 'th';
        },
        currency: {
            symbol: '£'
        }
    });

    numeral.locale('en-gb');
}
```

**Comment by alan-agius4** [comment]
Seems like the problem is not a problem as there is a `Breaking change: The locale function no longer loads locales, it only sets the current locale`

https://github.com/adamwdraper/Numeral-js

From what I understand you need to load the locales now

**Comment by stefanoric** [comment]
Here's how I managed to make it work:

```
var numeral = require('numeral');
var it = require('numeral/locales/it');

numeral.locale('it');

var number = numeral(10000);

console.log(number.format())
```

**Comment by o1o1o3** [comment]
@stefanoric I did not use angular and i have no require() directives, i use pure javascript and jquery with underscore, how i can handle this situation? I use numeral.js 2.0.6.

**Comment by stefanoric** [comment]
@dikkini I haven't used this library outside of node. I would suggest trying loading the locale objects the same way you load the library (e.g. ```<src="numeral.min.js "...```)

**Comment by Shiva127** [comment]
For **Vue.js with webpack**:

```
import numeral from 'numeral'
import 'numeral/locales/fr-ch'

numeral.locale('fr-ch')
```

**Comment by sebastienroul** [comment]
@adamwdraper : Suggestion  Could you had the @Shiva127 comment to the doc please, it would be very great - in the #Locales section... Thanks !

**Comment by sahin52** [comment]
This problem still goes on. Please make numeraljs give error when it can't load the locale.

**Comment by gatignoly** [comment]
I've added the following import and it's work :

`
import numeral from "numeral";
`
`
import "numeral/locales/fr";
`
