### ISSUE TITLE
Browser tests failing

### ISSUE THREAD

**Issue by seth-priya** [adamwdraper/Numeral-js#443]
Hi All,

I am trying to run the tests but they are failing for me. Firefox is being launched, then exiting 
Firefox 45.0.0 (Linux 0.0.0): Executed 164 of 164 SUCCESS (0.279 secs / 0.113 secs)
Warning: Task "karma:local" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.

All other tests are passing. Any pointers would be of great help

Thanks,
Priya

**Comment by seth-priya** [comment]
Could this be because I don't have Chrome installed? Are both browsers (Chrome and Firefox) required? Also, are any tests expected to be run after the browser is launched?

**Comment by adamwdraper** [comment]
Yes you must have both Chrome and Firefox installed to run the tests locally.  If you create a pull request the tests will get run on Travis Ci so you can see your results there are well.  The tests will launch the browser so you don't need to open them manually if that is what you are asking.
