### ISSUE TITLE
Space between symbol and value

### ISSUE THREAD

**Issue by marcelogarbin** [adamwdraper/Numeral-js#451]
I'm using the "pt-br" location, I'd like to add a space between the symbol and the value. When I add space it goes wrong.

Current example: R $1.000,1236 // space between R and $, but not value

*Correct example: R$ 1.000,1236 // current space between R$ and value

How can I adjust this?

**Comment by petr-bruzek** [comment]
The simillar case. I'm using "cs" locale, when I try to format value I get:

**Comment by marcelogarbin** [comment]
@kamihouse Seems to have fixed and made pull request but the same is not accepting, having accumulated several pull requests. Weird.

**Comment by AmmarHasan** [comment]
The library works fine for single letter currency symbols. Spacing issues for multi letter currency symbols has been fixed in this PR #461 . Simply replaces $ with current locale symbol. Depends on you were you put $ symbol

**Comment by ericpatrick** [comment]
I don't know if it's the same problem, but I find another issue with space between value and symbol:
`numeral("999999").format("0[.]0 a")` -> `1 k`
`numeral("999999").format("0[.]0a")` -> `1m`

**Comment by adamwdraper** [comment]
fixed in 2.0.5
