### ISSUE TITLE
Issues with multi letter currency symbols and spacing

### ISSUE THREAD

**Issue by marcusrognes** [adamwdraper/Numeral-js#461]
Locale: `numeral/locales/no`

When i use:
`numeral(521.67).format('0,0[.]00$')` 
i get `521.67kr`

when i use (make note of the space before the currency sign): 
`numeral(521.67).format('0,0[.]00 $')` 
i get `521.67k r`
instead of `521.67 kr` which is the correct way to format Norwegian currency.

**Comment by adamwdraper** [comment]
fixed in 2.0.5
