### ISSUE TITLE
merge conflicts were not being resolved in min/numeral.min.js !!

### ISSUE THREAD

**Issue by jiqiang** [adamwdraper/Numeral-js#485]
<img width="1004" alt="screen shot 2017-03-27 at 11 53 49 am" src="https://cloud.githubusercontent.com/assets/938491/24337048/1d86bb16-12e4-11e7-849c-02c7cc7713a4.png">

**Comment by carlostse** [comment]
Yes, occur in 2.0.5 but okay in 2.0.4

**Comment by adamwdraper** [comment]
Yes.  Fixing now.  Thanks

**Comment by adamwdraper** [comment]
Thanks
