### ISSUE TITLE
Is it possible to format numbers separated by space?

### ISSUE THREAD

**Issue by ardok** [adamwdraper/Numeral-js#516]
Say you have a number like `1000000` (1,000,000).
You want to format it so that it looks like:
`1 000 000`

10000000 -> `10 000 000`
999999999 -> `999 999 999`

You get the idea.

**Comment by tiesont** [comment]
You could probably abuse the locale setting to accomplish that: http://numeraljs.com/#locales

I would imagine something like this would work:

```js
numeral.register('locale', 'en-spaces', {
	delimiters: {
		thousands: ' ',
		decimal: '.'
	},
	abbreviations: {
		thousand: 'k',
		million: 'm',
		billion: 'b',
		trillion: 't'
	},
	ordinal: function(number) {
		var b = number % 10;
		return (~~(number % 100 / 10) === 1) ? 'th' :
			(b === 1) ? 'st' :
			(b === 2) ? 'nd' :
			(b === 3) ? 'rd' : 'th';
	},
	currency: {
		symbol: '$'
	}
});
```

And then 

```js
numeral.locale('en-spaces');
```

Somewhere before you started applying numeral. This is untested, though, so caveat emptor.

**Comment by ardok** [comment]
Hmm, I see.
It seems hacky though, like you said, "abuse".

I decided to just build my own helper function in my project.
I'll keep the locale register method in mind for future use cases when I really need it.
Thanks!

```
export function fullNumberFormat(num) {
  const result = [];

  while (num > 0) {
    if (num / 1000 < 1) {
      // It's not even in thousands, push the number
      result.push(num);
      break;
    }

    // `remainder` would be the last 3 digits
    const remainder = num % 1000;
    result.push(`${remainder}`);

    // Recalculate the remaining digits
    num = (num - remainder) / 1000;
  }

  /*
   `result` would look something like:
   [999, 234, 1]
   Hence, we need to reverse it first.
   */
  return result.reverse().reduce((final, r) => {
    final = `${final} ${'0'.repeat(3 - r.length)}${r}`;
    return final;
  }, '').trim();
}
```

**Comment by tiesont** [comment]
The only real advantage using a locale offers is that it can be made to match your regional settings, with perhaps the most important being the decimal separator. Otherwise, a .replace() call on the formatted value would (probably) work, too.

**Comment by ardok** [comment]
Ah, right. `replace` would have worked too.
