### ISSUE TITLE
Numeral instantiated with non-numeric values return zero

### ISSUE THREAD

**Issue by arcreative** [adamwdraper/Numeral-js#53]
This has probably not been changed as I'm expecting most are used to it defaulting to this behavior, but in my opinion, numeral('not a number') should definitely not evaluate to zero.  Is there a particular reason that [the top level parser](https://github.com/adamwdraper/Numeral-js/blob/master/numeral.js#L357) sets something to a number right after ascertaining that it isn't numeric?

I'm not expecting the default behavior to change for this, but couldn't there be some sort of "tolerant" setting that can be optionally disabled?

**Comment by wc-matteo** [comment]
This is stupid:

`numeral('9999999999999999999999999999999999999999').format()` outputs: `"NaN"`
`numeral('a').format()` outputs: `"0"`

and why `NaN` is a string?
