### ISSUE TITLE
Cannot use locales

### ISSUE THREAD

**Issue by JBoudMS** [adamwdraper/Numeral-js#555]
Inside my WebPack project, I am trying to use numeral.js like so:

`import numeral from 'numeral';
export default function() {
    numeral.locale('de');
    numeral(1234).format('0,0.000');
}`

If I don't register the locale, I get an error stating that the locale is undefined:
`numeral.js:198 Uncaught TypeError: Cannot read property 'delimiters' of undefined
    at numberToFormat (numeral.js:198)
    at Numeral.format (numeral.js:602)`

Otherwise if I register the locale, I get:
`Uncaught TypeError: de locale already registered.
    at Function.numeral.register (numeral.js:468)`

**Comment by JBoudMS** [comment]
As per #548, you just need to require('numeral/locales/' + language).
I feel that either you shouldn't need to require the language, or that it shouldn't throw an error if you try to set a language that hasn't been loaded.

Either way, the documentation for this desperately needs an update.

**Comment by lutangar** [comment]
I agree, at the moment, I'm using this to default to English if the locale doesn't exist:
```
  try {
    numeral.localeData(locale);
  } catch (e) {
    console.warn(`Couldn't find locale '${locale}', if implemented in 'numeral-js', you need to load it manually: require('numeral/locales/${locale}');`)
    locale = 'en';
  }
```

**Comment by tiesont** [comment]
Both the locales.js and the locales.min.js (in the min directory) files have all current locales - loading either will let you use the locale you want without needing to individually load a locale file.

**Comment by JBoudMS** [comment]
@tiesont Thank you very much for that.
I still feel that the documentation needs an update, but this works much nicer. Is there a repo for the documentation?

**Comment by tiesont** [comment]
@JBoudMS The only thing I'm aware of is the [gh-pages](https://github.com/adamwdraper/Numeral-js/tree/gh-pages) branch of this repo - I have no idea if @adamwdraper uses that for the docs. I assume so, as that's fairly standard for Github projects..

**Comment by JBoudMS** [comment]
Thanks @tiesont. I'll probably create a PR later with an update to the docs with the information discussed in here and #548.

**Comment by francisrod01** [comment]
@lutangar It's just import `numeral/locales` after `numeral` but it's not format from `en` currency to `user locale currency`. I think that can be improved.

**Comment by JonFranchi** [comment]
Just ran into this issue two years later and it looks like the documentation is still not up to date to reflect the need to manually require or import the language file.
