### ISSUE TITLE
NaN when formatting small numbers

### ISSUE THREAD

**Issue by muxa** [adamwdraper/Numeral-js#575]
`numeral('5e-7').format('0,0.00000000')` outputs `NaN`. This is happening for any format argument. 

`numeral('5e-7').value()` outputs `5e-7`

**Comment by perrosnk** [comment]
@adamwdraper I am experiencing the same problem. Any solutions or any reason this is happening?
Seems like an important bug

**Comment by perrosnk** [comment]
Dublicate of https://github.com/adamwdraper/Numeral-js/issues/563
@muxa please close this issue

**Comment by muxa** [comment]
Closing as this is a duplicate of #563
