### ISSUE TITLE
Parsing behavior is weird, invalid numeral values aren't always NaN

### ISSUE THREAD

**Issue by leosco** [adamwdraper/Numeral-js#581]
I'm playing around with sanitizing some bulk data and came across this:
```
numeral('2:23:57').value()
8637
numeral('hello').value()
null
isNaN(numeral('hello').value())
false
```
This contradicts the documentation [here](http://numeraljs.com/#create) which asserts two things:
1. `numeral('2:23:57')` should be invalid, but it isn't. Not sure how it's coming up with a value of 8637. Could this be a bug?
2. `numeral('some invalid string').value()` should equal NaN, but is instead `null`. This is a breaking issue because validating numerals using `isNaN()` no longer works!

**Comment by leosco** [comment]
Yeah, in general, Numeral's behavior is a bit strange. For example, 
```
numeral('11/22/17')
112217
```
it parses this kind of datestring as a valid number, but when you parse a full datestring
```
numeral(new Date().toString()).value()
NaN
```
you get `NaN`, as opposed to `null`? Very odd.

**Comment by Remixful** [comment]
Same with 1-18, value comes up as -118.

**Comment by liubko** [comment]
![screen shot 2018-06-08 at 1 29 38 pm](https://user-images.githubusercontent.com/4257937/41153646-03a33d6a-6b20-11e8-9f7f-d96255417500.png)
example from docs is broken
`numeral('2:23:57').value()` returns `8637`

**Comment by leosco** [comment]
Closing as this hasn't received any attention. I think Numeral is a great library and works well for the vast majority of use cases when you have formatted data intended to represent numbers.

**Comment by liubko** [comment]
@leosco what about this https://github.com/adamwdraper/Numeral-js/issues/581#issuecomment-395720712 maybe it worth to update the docs at least?
