### ISSUE TITLE
Is there a way for making the abbreviations with capital Letters?

### ISSUE THREAD

**Issue by NouranMahmoud** [adamwdraper/Numeral-js#585]
Hi,

I wanted these `10M` not `10m` and `10K` not `10k`. Is there a way for this?

**Comment by pythoncreate** [comment]
would like to know this as well. good question!

**Comment by pythoncreate** [comment]
ok this is working for me---hope it works for you!

```
var numeral = require('numeral');

numeral.register('locale', 'us', {
    delimiters: {
        thousands: ' ',
        decimal: '.'
    },
    abbreviations: {
        thousand: 'K',
        million: 'M',
        billion: 'B',
        trillion: 'T'
    },
    ordinal : function (number) {
        return number === 1 ? 'er' : 'ème';
    },
    currency: {
        symbol: '$'
    }
});

// switch between locales
numeral.locale('us');
```

**Comment by NouranMahmoud** [comment]
So, we will need to re-write our locale files? I wanted a way to change the abbreviations out of the box actually. I will make a PR for this if there is no way other than this.

I'd propose changing this through the `.format` function like the followings:- 
- `.format('0.0a)` (a) for small letters and `.format('0.0A')` (A) for capital letters.

What do you think?

**Comment by khan4019** [comment]
Be careful. 10M means 10 million where 10m means mili. They are not same. https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes

**Comment by mak2014** [comment]
I did this for vuejs app, it may help.

`Vue.filter('capitalize', function (string) {
  var capitalFirst = string.toUpperCase()
  return capitalFirst
})`

For the display

`{{ total_count | numeral('0,0 a') | capitalize }}`

**Comment by nao-de** [comment]
So did this ever get fixed or just closed? @NouranMahmoud

**Comment by NouranMahmoud** [comment]
Just closed. @de-ocampo

**Comment by rimday** [comment]
This is not necessary. You only need to add uppercase css
```
<span class="uppercase">{{ numeral(50000).format('0a) }}</span>

<style>
    .uppercase { text-transform: uppercase; }
</style>

```

**Comment by Standaa** [comment]
As pointed out by @khan4019 this is a convention problem.
While easy to fix in css, I feel like this should be OOB in the library as it is breaking existing international conventions.
An easy fix would be defaulting to the convention rather than displaying everything lowercase.

**Comment by uooopss** [comment]
As a temporary workaround, I did this:

`numeral(1000000).format('0,0.[0]a').toLowerCase().replace(/[a-z]\b/g, (c) => c.toUpperCase())`
