### ISSUE TITLE
Values smaller than 1.0e-6 are parsed incorrectly by numeral._.toFixed

### ISSUE THREAD

**Issue by smithcyr** [adamwdraper/Numeral-js#594]
https://github.com/adamwdraper/Numeral-js/blob/7de892ffb438af6e63b9c4f6aff0c9bc3932f09f/numeral.js#L398

1e-7.toString() returns "1e-7" which breaks the string coercion hack above

**Comment by michaeltomasik** [comment]
@smithcyr it is duplicate https://github.com/adamwdraper/Numeral-js/issues/512

**Comment by michaeltomasik** [comment]
I forked repo and changed it so the output of `1e-7` should return 0.0000007
https://github.com/michaeltomasik/Numeral-js

**Comment by MrCsabaToth** [comment]
Why is this closed?
