### ISSUE TITLE
Expose languages collection

### ISSUE THREAD

**Issue by carlospombeiro** [adamwdraper/Numeral-js#62]
Hello,
numeral should expose the languages collection. This way the language definition is available.

In my case I'm removing the thousands delimiter and currency symbol from an input text and test if it's a number.

Example
    var langData = numeral.languages()[numeral.language()];
    var re = new RegExp('[' + langData.delimiters.thousands + langData.currency.symbol + ']', "g");
    var rawValue = value.replace(re, '');
    var isNumber = Number(rawValue);

Thanks

**Comment by adamwdraper** [comment]
numeral has a validate function to accomplish this.
