### ISSUE TITLE
numeral(0.99991).format('0.00') result 1.0

### ISSUE THREAD

**Issue by Tpona** [adamwdraper/Numeral-js#625]
It is right?
numeral(0.99991).format('0.00') result 1.0

How to become 
numeral(0.99991).format('0.00') result 0.99 
?

Thx

**Comment by gokhangencer** [comment]
numeral(0.99991).format('0.00', Math.floor) => results 0.99

**Comment by Tpona** [comment]
Thx
Spasibo, gokhangencer )
