### ISSUE TITLE
Formatting large number return inaccurate number

### ISSUE THREAD

**Issue by hqtoan94** [adamwdraper/Numeral-js#696]
When I test my app by entering large number with decimal, it returns the wrong number. Like below:

```
numeral('999,999,999,999,999.68').format('0.00')
> 999999999999999.63
```

**Comment by fogine** [comment]
The number you are trying to parse is too large and it doesnt fit the last decimal place. Javascript has 64bit numbers..

**Comment by hqtoan94** [comment]
Just wanna put this here so that other people might face with the same issue.
https://stackoverflow.com/questions/54800022/why-max-digits-with-decimal-in-javascript-are-only-16#answer-54803254

Thanks @fogine , I'm gonna close this issue.
