### ISSUE TITLE
Formatting of Negative currencies with negative symbol at the end ($ n-)

### ISSUE THREAD

**Issue by anilchempath** [adamwdraper/Numeral-js#93]
We are trying to format the negative curecny for nl-NL . So the negative pattern is  ' $ n- '  .
 So I have formatted the currecny  as `numeral("-102300.00").format("$10,00.00-")` but its giving wrong  results .  Am i doing some thing wrong how can I achieve this.

Thanks in Advance .

**Comment by adamwdraper** [comment]
Duplicate of #89
